# Feature Encoding - Ordinal Encoding

## Introduction to Feature Encoding

Feature Encoding is a data preprocessing technique used to convert categorical data into numerical values so that machine learning algorithms can understand and process the information.

Most machine learning algorithms work with numerical data and cannot directly interpret text-based categories. Therefore, categorical features must be transformed into a numerical format before model training.

---

## What is Ordinal Data?

Ordinal data is a type of categorical data where the categories have a meaningful order or ranking.

In ordinal data, one category can be considered higher or lower than another based on a natural sequence.

### Examples

#### Education Level

- High School
- Bachelor's
- Master's
- PhD

#### Customer Satisfaction

- Poor
- Average
- Good
- Excellent

#### T-Shirt Size

- Small
- Medium
- Large

These categories follow a logical order, making them suitable for ordinal encoding.

---

## What is Ordinal Encoding?

Ordinal Encoding is a feature encoding technique used to convert ordinal categorical data into numerical values while preserving the natural order of the categories.

Each category is assigned a unique integer based on its ranking.

### Example

| Education Level | Encoded Value |
|----------------|---------------|
| High School | 1 |
| Bachelor's | 2 |
| Master's | 3 |
| PhD | 4 |

The numerical values represent the order of the categories rather than their magnitude.

---

## Why Use Ordinal Encoding?

- Converts ordered categorical data into numerical form.
- Preserves the ranking information present in the feature.
- Makes the data suitable for machine learning algorithms.
- Simple and efficient preprocessing technique.

---

## Dataset Used

In this notebook, the **Salary Dataset** is used to demonstrate Ordinal Encoding.

The dataset contains employee information such as:

- Age
- Gender
- Education Level
- Job Title
- Years of Experience
- Salary

Among these features, **Education Level** is an ordinal feature because it follows a natural hierarchy:

High School < Bachelor's < Master's < PhD

---

## Objective

The objective of this notebook is to:

1. Load the Salary Dataset.
2. Identify the ordinal feature.
3. Apply Ordinal Encoding to the Education Level column.
4. Compare the data before and after encoding.
5. Prepare the dataset for further machine learning preprocessing steps.

In [7]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Raksha\OneDrive\Desktop\Encoding\Salary Data.csv")
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [8]:
df['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD', nan], dtype=object)

In [9]:
df['Education Level'].isnull().sum()

np.int64(2)

In [10]:
df['Education Level'] = df['Education Level'].fillna(
    df['Education Level'].mode()[0]
)

In [11]:
df['Education Level'].isnull().sum()

np.int64(0)

In [12]:
education_order = {
    "Bachelor's": 1,
    "Master's": 2,
    "PhD": 3
}

df['Education Level'] = df['Education Level'].map(education_order)

In [8]:
df[['Education Level']].head()

   Education Level
0                1
1                2
2                3
3                1
4                2

## Label Encoding

Label Encoding is a technique used to convert categorical values into numerical labels.

Each unique category is assigned a unique integer value.

In this notebook, Label Encoding is applied to the Education Level feature to transform categorical education levels into numerical form.

### Example

| Education Level | Encoded Value |
|----------------|---------------|
| Bachelor's | 0 |
| Master's | 1 |
| PhD | 2 |

Label Encoding is simple and useful for converting categorical data into machine-readable format.

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Education_Level_Label'] = le.fit_transform(df['Education Level'])

df[['Education Level','Education_Level_Label']].head()

   Education Level  Education_Level_Label
0                1                      0
1                2                      1
2                3                      2
3                1                      0
4                2                      1

In [14]:
import os
os.getcwd()

'C:\\Users\\Raksha\\anaconda_projects\\2c228e97-2958-44a4-ae40-ccc61fc3b4a8'

In [15]:
import os

for file in os.listdir():
    if file.endswith(".ipynb"):
        print(file)

Encode.ipynb

In [16]:
print(os.getcwd())
print(os.listdir())

C:\Users\Raksha\anaconda_projects\2c228e97-2958-44a4-ae40-ccc61fc3b4a8
['.ipynb_checkpoints', 'Encode.ipynb']

In [17]:
os.listdir()

['.ipynb_checkpoints', 'Encode.ipynb']

# One Hot Encoding

## Introduction

One Hot Encoding is a feature encoding technique used to convert nominal categorical data into numerical format.

Unlike ordinal data, nominal categories do not have a natural order or ranking. Therefore, assigning numerical labels directly may introduce incorrect relationships between categories.

One Hot Encoding creates a separate binary column for each category.

### Example

| Gender |
|----------|
| Male |
| Female |

becomes

| Gender_Male |
|-------------|
| 1 |
| 0 |

Each encoded column contains either:

- 1 → Category is present
- 0 → Category is absent

This approach prevents machine learning algorithms from assuming any order between categories.

---

## Why Use One Hot Encoding?

- Suitable for nominal data.
- Prevents false ordering between categories.
- Easy to interpret.
- Widely used in machine learning preprocessing.

---

## Features Selected

The Salary Dataset contains the following nominal features:

- Gender
- Job Title

In this section, One Hot Encoding will be applied to these features to convert them into numerical representations suitable for machine learning models.

In [18]:
df['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [19]:
df['Gender'].isnull().sum()

np.int64(2)

In [20]:
df['Gender'] = df['Gender'].fillna(
    df['Gender'].mode()[0]
)

In [21]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [22]:
pd.get_dummies(df['Gender'])

     Female   Male
0     False   True
1      True  False
2     False   True
3      True  False
4     False   True
..      ...    ...
370    True  False
371   False   True
372    True  False
373   False   True
374    True  False

[375 rows x 2 columns]

In [23]:
pd.get_dummies(df['Gender'], drop_first=True)

      Male
0     True
1    False
2     True
3    False
4     True
..     ...
370  False
371   True
372  False
373   True
374  False

[375 rows x 1 columns]

In [24]:
pd.get_dummies(df['Gender'], drop_first=True).head()

    Male
0   True
1  False
2   True
3  False
4   True

In [25]:
df = pd.get_dummies(
    df,
    columns=['Gender'],
    drop_first=True
)

df.head()

,Age,Education Level,Job Title,Years of Experience,Salary,Education_Level_Label,Gender_Male
0,32.0,1,Software Engineer,5.0,90000.0,0,True
1,28.0,2,Data Analyst,3.0,65000.0,1,False
2,45.0,3,Senior Manager,15.0,150000.0,2,True
3,36.0,1,Sales Associate,7.0,60000.0,0,False
4,52.0,2,Director,20.0,200000.0,1,True

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
df['Job Title'].nunique()

174

In [29]:
df['Job Title'].unique()

array(['Software Engineer', 'Data Analyst', 'Senior Manager',
       'Sales Associate', 'Director', 'Marketing Analyst',
       'Product Manager', 'Sales Manager', 'Marketing Coordinator',
       'Senior Scientist', 'Software Developer', 'HR Manager',
       'Financial Analyst', 'Project Manager', 'Customer Service Rep',
       'Operations Manager', 'Marketing Manager', 'Senior Engineer',
       'Data Entry Clerk', 'Sales Director', 'Business Analyst',
       'VP of Operations', 'IT Support', 'Recruiter', 'Financial Manager',
       'Social Media Specialist', 'Software Manager', 'Junior Developer',
       'Senior Consultant', 'Product Designer', 'CEO', 'Accountant',
       'Data Scientist', 'Marketing Specialist', 'Technical Writer',
       'HR Generalist', 'Project Engineer', 'Customer Success Rep',
       'Sales Executive', 'UX Designer', 'Operations Director',
       'Network Engineer', 'Administrative Assistant',
       'Strategy Consultant', 'Copywriter', 'Account Manager',
       'Director of Marketing', 'Help Desk Analyst',
       'Customer Service Manager', 'Business Intelligence Analyst',
       'Event Coordinator', 'VP of Finance', 'Graphic Designer',
       'UX Researcher', 'Social Media Manager', 'Director of Operations',
       'Senior Data Scientist', 'Junior Accountant',
       'Digital Marketing Manager', 'IT Manager',
       'Customer Service Representative', 'Business Development Manager',
       'Senior Financial Analyst', 'Web Developer', 'Research Director',
       'Technical Support Specialist', 'Creative Director',
       'Senior Software Engineer', 'Human Resources Director',
       'Content Marketing Manager', 'Technical Recruiter',
       'Sales Representative', 'Chief Technology Officer',
       'Junior Designer', 'Financial Advisor', 'Junior Account Manager',
       'Senior Project Manager', 'Principal Scientist',
       'Supply Chain Manager', 'Senior Marketing Manager',
       'Training Specialist', 'Research Scientist',
       'Junior Software Developer', 'Public Relations Manager',
       'Operations Analyst', 'Product Marketing Manager',
       'Senior HR Manager', 'Junior Web Developer',
       'Senior Project Coordinator', 'Chief Data Officer',
       'Digital Content Producer', 'IT Support Specialist',
       'Senior Marketing Analyst', 'Customer Success Manager',
       'Senior Graphic Designer', 'Software Project Manager',
       'Supply Chain Analyst', 'Senior Business Analyst',
       'Junior Marketing Analyst', 'Office Manager', 'Principal Engineer',
       'Junior HR Generalist', 'Senior Product Manager',
       'Junior Operations Analyst', 'Senior HR Generalist',
       'Sales Operations Manager', 'Senior Software Developer',
       'Junior Web Designer', 'Senior Training Specialist',
       'Senior Research Scientist', 'Junior Sales Representative',
       'Junior Marketing Manager', 'Junior Data Analyst',
       'Senior Product Marketing Manager', 'Junior Business Analyst',
       'Senior Sales Manager', 'Junior Marketing Specialist',
       'Junior Project Manager', 'Senior Accountant', 'Director of Sales',
       'Junior Recruiter', 'Senior Business Development Manager',
       'Senior Product Designer', 'Junior Customer Support Specialist',
       'Senior IT Support Specialist', 'Junior Financial Analyst',
       'Senior Operations Manager', 'Director of Human Resources',
       'Junior Software Engineer', 'Senior Sales Representative',
       'Director of Product Management', 'Junior Copywriter',
       'Senior Marketing Coordinator', 'Senior Human Resources Manager',
       'Junior Business Development Associate', 'Senior Account Manager',
       'Senior Researcher', 'Junior HR Coordinator',
       'Director of Finance', 'Junior Marketing Coordinator', nan,
       'Junior Data Scientist', 'Senior Operations Analyst',
       'Senior Human Resources Coordinator', 'Senior UX Designer',
       'Junior Product Manager', 'Senior Marketing Specialist',
       'Senior IT Project Manager', 'Senior Quality Assurance Analyst',
       'Director of Sales and Marketing', 'Senior Account Executive',
       'Director of Business Development', 'Junior Social Media Manager',
       'Senior Human Resources Specialist', 'Senior Data Analyst',
       'Director of Human Capital', 'Junior Advertising Coordinator',
       'Junior UX Designer', 'Senior Marketing Director',
       'Senior IT Consultant', 'Senior Financial Advisor',
       'Junior Business Operations Analyst',
       'Junior Social Media Specialist',
       'Senior Product Development Manager', 'Junior Operations Manager',
       'Senior Software Architect', 'Junior Research Scientist',
       'Senior Financial Manager', 'Senior HR Specialist',
       'Senior Data Engineer', 'Junior Operations Coordinator',
       'Director of HR', 'Senior Operations Coordinator',
       'Junior Financial Advisor', 'Director of Engineering'],
      dtype=object)

In [30]:
job_counts = df['Job Title'].value_counts()

job_counts.head(20)

Job Title
Director of Marketing                    12
Director of Operations                   11
Senior Business Analyst                  10
Senior Marketing Manager                  9
Senior Marketing Analyst                  9
Junior Business Analyst                   8
Senior Project Manager                    7
Senior Data Scientist                     7
Junior Business Development Associate     7
Junior Financial Analyst                  7
Senior Financial Analyst                  7
Senior Product Manager                    6
Senior Software Engineer                  6
Junior Marketing Coordinator              6
Senior Project Coordinator                5
Junior Operations Analyst                 5
Junior Project Manager                    5
Senior Financial Manager                  5
Senior Product Designer                   5
Senior Operations Manager                 5
Name: count, dtype: int64

In [31]:
df['Job Title'].value_counts().head(20)

Job Title
Director of Marketing                    12
Director of Operations                   11
Senior Business Analyst                  10
Senior Marketing Manager                  9
Senior Marketing Analyst                  9
Junior Business Analyst                   8
Senior Project Manager                    7
Senior Data Scientist                     7
Junior Business Development Associate     7
Junior Financial Analyst                  7
Senior Financial Analyst                  7
Senior Product Manager                    6
Senior Software Engineer                  6
Junior Marketing Coordinator              6
Senior Project Coordinator                5
Junior Operations Analyst                 5
Junior Project Manager                    5
Senior Financial Manager                  5
Senior Product Designer                   5
Senior Operations Manager                 5
Name: count, dtype: int64

In [32]:
df['Job Title'].value_counts().tail(20)

Job Title
Senior IT Project Manager             1
Senior Quality Assurance Analyst      1
Director of Sales and Marketing       1
Senior Human Resources Coordinator    1
Senior Marketing Director             1
Junior UX Designer                    1
Junior Advertising Coordinator        1
Director of Human Capital             1
Senior Human Resources Specialist     1
Junior Social Media Manager           1
Director of Business Development      1
Senior Account Executive              1
Junior Research Scientist             1
Senior Software Architect             1
Senior Product Development Manager    1
Junior Social Media Specialist        1
Junior Operations Coordinator         1
Senior HR Specialist                  1
Director of HR                        1
Junior Financial Advisor              1
Name: count, dtype: int64

In [34]:
job_counts = df['Job Title'].value_counts()

In [35]:
threshold = 10

In [36]:
common_jobs = job_counts[job_counts >= threshold].index

df['Job Title'] = df['Job Title'].apply(
    lambda x: x if x in common_jobs else 'Other'
)

In [37]:
df['Job Title'].value_counts()

Job Title
Other                      342
Director of Marketing       12
Director of Operations      11
Senior Business Analyst     10
Name: count, dtype: int64

In [38]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop='first', sparse_output=False)

job_encoded = encoder.fit_transform(df[['Job Title']])

In [39]:
job_encoded.shape

(375, 3)

In [40]:
job_encoded_df = pd.DataFrame(
    job_encoded,
    columns=encoder.get_feature_names_out(['Job Title'])
)

job_encoded_df.head()

,Job Title_Director of Operations,Job Title_Other,Job Title_Senior Business Analyst
0,0.0,1.0,0.0
1,0.0,1.0,0.0
2,0.0,1.0,0.0
3,0.0,1.0,0.0
4,0.0,1.0,0.0

In [41]:
df = pd.concat([df, job_encoded_df], axis=1)

In [42]:
df.drop('Job Title', axis=1, inplace=True)

In [43]:
df.head()

,Age,Education Level,Years of Experience,Salary,Education_Level_Label,Gender_Male,Job Title_Director of Operations,Job Title_Other,Job Title_Senior Business Analyst
0,32.0,1,5.0,90000.0,0,True,0.0,1.0,0.0
1,28.0,2,3.0,65000.0,1,False,0.0,1.0,0.0
2,45.0,3,15.0,150000.0,2,True,0.0,1.0,0.0
3,36.0,1,7.0,60000.0,0,False,0.0,1.0,0.0
4,52.0,2,20.0,200000.0,1,True,0.0,1.0,0.0

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 9 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                373 non-null    float64
 1   Education Level                    375 non-null    int64
 2   Years of Experience                373 non-null    float64
 3   Salary                             373 non-null    float64
 4   Education_Level_Label              375 non-null    int64
 5   Gender_Male                        375 non-null    bool
 6   Job Title_Director of Operations   375 non-null    float64
 7   Job Title_Other                    375 non-null    float64
 8   Job Title_Senior Business Analyst  375 non-null    float64
dtypes: bool(1), float64(6), int64(2)
memory usage: 23.9 KB